# Generated by Django 5.1.6 on 2025-03-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_plaintes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='signalements/audios/'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='signalements/images/'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='signalements/videos/'),
        ),
    ]
