# Generated by Django 5.1.6 on 2025-03-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_plaintes', '0002_signalement_audio_signalement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='signalement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
